### ISSUE TITLE
Idk how to comment on this

### ISSUE THREAD

**Issue by nicosogangstar** [BurningPixel/LispyCalculator#1]
eq = '(+ (+ 1 1) (+ 1 1))'
    
    parens = [
        [i, v] for i, v in enumerate(eq)
            if v in '()'
    ]
    
    
    non_nested_nodes = []
    
    # IDK WHY THIS WORKS
    for i in range(len(parens)):
        if i < len(parens) -1:
            if parens[i][1] == '(' and parens[i+1][1] == ')':
                non_nested_nodes += parens[i],parens[i+1]
                
    
    #p#rint(non_nested_nodes)
    
    nnn = non_nested_nodes
    
    for i in range(len(non_nested_nodes)):
        
        # gets olny one (+ 1 1) atm
        # get sets of nodes and sub strings
        if i % 2 == 0 and i < len(nnn):
            start = nnn[i][0]
            end = nnn[i+1][0]
            print(
                eq[start: -end]
            )

**Comment by BurningPixel** [comment]
Thanks for letting me post from your account!
